import {NgModule} from '@angular/core';
import {CommonModule} from "@angular/common";
import {MatIconModule, MatIconRegistry} from "@angular/material/icon";
import {DomSanitizer} from "@angular/platform-browser";

@NgModule({
  imports: [
    MatIconModule,
    CommonModule
  ],
  exports: [
    MatIconModule
  ]
})
export class IconModule {
  constructor(
    private matIconRegistry: MatIconRegistry,
    private domSanitizer: DomSanitizer
  ) {
    matIconRegistry.addSvgIcon(
      'github',
      domSanitizer.bypassSecurityTrustResourceUrl('assets/icons/mat-github.svg'),
    );
    matIconRegistry.addSvgIcon(
      'linkedin',
      domSanitizer.bypassSecurityTrustResourceUrl('assets/icons/mat-linkedin.svg'),
    );
    matIconRegistry.addSvgIcon(
      'palette',
      domSanitizer.bypassSecurityTrustResourceUrl('assets/icons/mat-palette.svg'),
    );
    matIconRegistry.addSvgIcon(
      'one',
      domSanitizer.bypassSecurityTrustResourceUrl('assets/icons/mat-one.svg'),
    );
    matIconRegistry.addSvgIcon(
      'key',
      domSanitizer.bypassSecurityTrustResourceUrl('assets/icons/mat-key.svg'),
    );
    matIconRegistry.addSvgIcon(
      'person',
      domSanitizer.bypassSecurityTrustResourceUrl('assets/icons/mat-person.svg'),
    );
    matIconRegistry.addSvgIcon(
      'thumb',
      domSanitizer.bypassSecurityTrustResourceUrl('assets/icons/mat-thumb.svg'),
    );
    matIconRegistry.addSvgIcon(
      'earth',
      domSanitizer.bypassSecurityTrustResourceUrl('assets/icons/mat-earth.svg'),
    );
    matIconRegistry.addSvgIcon(
      'rocket',
      domSanitizer.bypassSecurityTrustResourceUrl('assets/icons/mat-rocket.svg'),
    );
    matIconRegistry.addSvgIcon(
      'lamp',
      domSanitizer.bypassSecurityTrustResourceUrl('assets/icons/mat-lamp.svg'),
    );
    matIconRegistry.addSvgIcon(
      'leaf',
      domSanitizer.bypassSecurityTrustResourceUrl('assets/icons/mat-leaf.svg'),
    );
    matIconRegistry.addSvgIcon(
      'pet',
      domSanitizer.bypassSecurityTrustResourceUrl('assets/icons/mat-pet.svg'),
    );
    matIconRegistry.addSvgIcon(
      'health',
      domSanitizer.bypassSecurityTrustResourceUrl('assets/icons/mat-health.svg'),
    );
    matIconRegistry.addSvgIcon(
      'sad',
      domSanitizer.bypassSecurityTrustResourceUrl('assets/icons/mat-sad.svg'),
    );
    matIconRegistry.addSvgIcon(
      'medal',
      domSanitizer.bypassSecurityTrustResourceUrl('assets/icons/mat-medal.svg'),
    );
    matIconRegistry.addSvgIcon(
      'gavel',
      domSanitizer.bypassSecurityTrustResourceUrl('assets/icons/mat-gavel.svg'),
    );
    matIconRegistry.addSvgIcon(
      'diamond',
      domSanitizer.bypassSecurityTrustResourceUrl('assets/icons/mat-diamond.svg'),
    );
    matIconRegistry.addSvgIcon(
      'moon',
      domSanitizer.bypassSecurityTrustResourceUrl('assets/icons/mat-moon.svg'),
    );
    matIconRegistry.addSvgIcon(
      'eldery',
      domSanitizer.bypassSecurityTrustResourceUrl('assets/icons/mat-eldery.svg'),
    );
    matIconRegistry.addSvgIcon(
      'skull',
      domSanitizer.bypassSecurityTrustResourceUrl('assets/icons/mat-skull.svg'),
    );
    matIconRegistry.addSvgIcon(
      'egg',
      domSanitizer.bypassSecurityTrustResourceUrl('assets/icons/mat-egg.svg'),
    );
    matIconRegistry.addSvgIcon(
      'trophy',
      domSanitizer.bypassSecurityTrustResourceUrl('assets/icons/mat-trophy.svg'),
    );
    matIconRegistry.addSvgIcon(
      'cart',
      domSanitizer.bypassSecurityTrustResourceUrl('assets/icons/mat-cart.svg'),
    );
    matIconRegistry.addSvgIcon(
      'tooth',
      domSanitizer.bypassSecurityTrustResourceUrl('assets/icons/mat-tooth.svg'),
    );
    matIconRegistry.addSvgIcon(
      'volcano',
      domSanitizer.bypassSecurityTrustResourceUrl('assets/icons/mat-volcano.svg'),
    );
    matIconRegistry.addSvgIcon(
      'bones',
      domSanitizer.bypassSecurityTrustResourceUrl('assets/icons/mat-bones.svg'),
    );
    matIconRegistry.addSvgIcon(
      'comm',
      domSanitizer.bypassSecurityTrustResourceUrl('assets/icons/mat-comm.svg'),
    );
    matIconRegistry.addSvgIcon(
      'cognition',
      domSanitizer.bypassSecurityTrustResourceUrl('assets/icons/mat-cognition.svg'),
    );
    matIconRegistry.addSvgIcon(
      'footprints',
      domSanitizer.bypassSecurityTrustResourceUrl('assets/icons/mat-footprints.svg'),
    );
    matIconRegistry.addSvgIcon(
      'pill',
      domSanitizer.bypassSecurityTrustResourceUrl('assets/icons/mat-pill.svg'),
    );
    matIconRegistry.addSvgIcon(
      'mask',
      domSanitizer.bypassSecurityTrustResourceUrl('assets/icons/mat-mask.svg'),
    );
    matIconRegistry.addSvgIcon(
      'flower',
      domSanitizer.bypassSecurityTrustResourceUrl('assets/icons/mat-flower.svg'),
    );
    matIconRegistry.addSvgIcon(
      'bomb',
      domSanitizer.bypassSecurityTrustResourceUrl('assets/icons/mat-bomb.svg'),
    );
    matIconRegistry.addSvgIcon(
      'raven',
      domSanitizer.bypassSecurityTrustResourceUrl('assets/icons/mat-raven.svg'),
    );
    matIconRegistry.addSvgIcon(
      'lock',
      domSanitizer.bypassSecurityTrustResourceUrl('assets/icons/mat-lock.svg'),
    );
    matIconRegistry.addSvgIcon(
      'bug',
      domSanitizer.bypassSecurityTrustResourceUrl('assets/icons/mat-bug.svg'),
    );
    matIconRegistry.addSvgIcon(
      'build',
      domSanitizer.bypassSecurityTrustResourceUrl('assets/icons/mat-build.svg'),
    );
    matIconRegistry.addSvgIcon(
      'anchor',
      domSanitizer.bypassSecurityTrustResourceUrl('assets/icons/mat-anchor.svg'),
    );
  }
}
